[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ann-engine"
version = "0.1.0"
description = "Neural Network framework built from scratch using NumPy"
authors = [
  { name="Biswas" }
]
dependencies = [
  "numpy"
]

[tool.setuptools.packages.find]
where = ["."]
